#!/usr/bin/env bash
#set -x
unset GIT_LITERAL_PATHSPECS

pre-commit run --all-files -c $(git config --get core.hookspath)/.pre-commit-config.yaml

terra_fmt () {
    if [ -f '.module' ]
    then
        terra_fmt_modules
    fi
}

terra_fmt_modules () {
    if [ ! -f 'docs/README.md' ]
    then
        echo 'Terraform repos must have a `docs/README.md`'
        exit -3
    fi

    cat docs/README.md > ./README.md
    terraform-docs md . >> README.md
}

go_commit () {
    echo 'Stub for golang pre-commit hooks'
}

py_commit () {
    echo 'stub for python pre-commit hooks'
    #find . -name '__init__.py' -exec bash -c 'pylint --ignore=psycopg2 $(dirname {})' \;
}

declare -A FILTERS=(
    [tf]=terra_fmt
    [go]=go_commit
    [py]=py_commit)

for k in ${!FILTERS[@]}
do
    if [ "x$(git ls-files -- *.${k} | xargs)" != "x" ]
    then
        ${FILTERS[$k]}
    fi
done

exit 0
